name: Deploy 🚀

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: deploy
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install NPM packages 📦
        run: npm clean-install
      # Runs a single command using the runners shell
      - name: Build app for prod 🛠💻
        run: |
          npx ng build --prod
          mkdir -p bin/deployment
          cp -r app.yaml dist/eggx-external/ bin/deployment/
          cd bin/deployment
          mv eggx-external/ www/
          echo "Build ready for deployment at $(pwd)"
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy test app to GAE 🚀
        run: |
          cd bin/deployment
          gcloud app deploy app.yaml
